# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionAtmosferica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField()),
                ('humedad', models.IntegerField()),
                ('estacion', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None)),
                ('titulo', models.CharField(blank=True, default='', max_length=150)),
                ('es_meta', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('H', 'Hoja'), ('N', 'Ninguno'), ('F', 'Flor'), ('T', 'Tallo'), ('R', 'Raiz')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('hecho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='greengarden.Hecho')),
                ('imagen', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=250)),
                ('tratamiento', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='regla',
            name='conclusion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='greengarden.Hecho'),
        ),
        migrations.AddField(
            model_name='hecho',
            name='reglas',
            field=models.ManyToManyField(blank=True, to='greengarden.Regla'),
        ),
    ]
