# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hecho',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='hecho',
            name='valor',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, '')], default=None),
        ),
    ]
