# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0002_auto_20160810_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='es_monitorizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='valor',
            field=models.NullBooleanField(choices=[(None, ''), (False, 'No'), (True, 'Yes')], default=None),
        ),
    ]
