# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0002_regla'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='reglas',
            field=models.ManyToManyField(to='greengarden.Regla'),
        ),
    ]
