# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0003_hecho_reglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='conclusion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='greengarden.Hecho'),
        ),
    ]
