# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0003_auto_20160814_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionatmosferica',
            name='metas',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
