# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0004_regla_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='es_meta',
            field=models.BooleanField(default=False),
        ),
    ]
