# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0004_condicionatmosferica_metas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tratamiento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='valor',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
