# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0006_parametrosatmosfericos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='pregunta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
