# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0006_auto_20160622_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regla',
            name='conclusion',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='greengarden.Hecho'),
        ),
    ]
