# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0007_hecho_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='valor',
            field=models.NullBooleanField(choices=[(None, ''), (False, 'No'), (True, 'Yes')], default=None),
        ),
    ]
