# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0008_auto_20160917_0451'),
        ('greengarden', '0007_estado'),
    ]

    operations = [
    ]
