# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0009_auto_20160622_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='reglas',
            field=models.ManyToManyField(blank=True, null=True, to='greengarden.Regla'),
        ),
    ]
