# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.CharField(choices=[('RS', 'Riesgo'), ('AS', 'Controlado'), ('IN', 'Infectado')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='valor',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
