# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0011_auto_20160622_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho',
            name='titulo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
