# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0013_auto_20160703_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
