# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0016_hecho_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('hecho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='greengarden.Hecho')),
                ('imagen', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('tratamiento', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('T', 'Tallo'), ('F', 'Flor'), ('R', 'Raiz'), ('N', 'Ninguno'), ('H', 'Hoja')], default='N', max_length=1),
        ),
    ]
