# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0018_auto_20160712_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tratamiento',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('R', 'Raiz'), ('F', 'Flor'), ('T', 'Tallo'), ('H', 'Hoja'), ('N', 'Ninguno')], default='N', max_length=1),
        ),
    ]
