# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0020_auto_20160716_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('T', 'Tallo'), ('F', 'Flor'), ('H', 'Hoja'), ('R', 'Raiz'), ('N', 'Ninguno')], default='N', max_length=1),
        ),
    ]
