# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import greengarden.models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0022_auto_20160716_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechosComparidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField()),
                ('humedad', models.IntegerField(verbose_name=greengarden.models.Hecho)),
                ('estacion', models.IntegerField(verbose_name=greengarden.models.Hecho)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('R', 'Raiz'), ('H', 'Hoja'), ('T', 'Tallo'), ('N', 'Ninguno'), ('F', 'Flor')], default='N', max_length=1),
        ),
    ]
