# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0024_auto_20160719_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionAtmosferica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField()),
                ('humedad', models.IntegerField()),
                ('estacion', models.IntegerField()),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CondicionesAtmosfericas',
        ),
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('R', 'Raiz'), ('H', 'Hoja'), ('N', 'Ninguno'), ('F', 'Flor'), ('T', 'Tallo')], default='N', max_length=1),
        ),
    ]
