# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greengarden', '0025_auto_20160719_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionatmosferica',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='categoria',
            field=models.CharField(choices=[('F', 'Flor'), ('N', 'Ninguno'), ('H', 'Hoja'), ('T', 'Tallo'), ('R', 'Raiz')], default='N', max_length=1),
        ),
    ]
